name: Build image
run-name: Build image - started by ${{ github.actor }}
on: [workflow_dispatch, pull_request, push]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo '456'